# Generated by Django 6.0.1 on 2026-01-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Kolhapur', 'Kolhapur'), ('Solapur', 'Solapur')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Below SSC', 'Below SSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('Under-Graduate', 'Under-Graduate'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=50, null=True),
        ),
    ]
