# Generated by Django 6.0.1 on 2026-01-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_course_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('City', 'City'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Kolhapur', 'Kolhapur'), ('Solapur', 'Solapur')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Below SSC', 'Below SSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('Under-Graduate', 'Under-Graduate'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], default='N/A', max_length=50, null=True),
        ),
    ]
