# Generated by Django 6.0.1 on 2026-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, choices=[('City', 'City'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Kolhapur', 'Kolhapur'), ('Solapur', 'Solapur')], default='Pune', max_length=50, null=True),
        ),
    ]
