# Generated by Django 6.0.1 on 2026-01-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Kolhapur', 'Kolhapur'), ('Solapur', 'Solapur')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Below SSC', 'Below SSC'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('Under-Graduate', 'Under-Graduate'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=50, null=True),
        ),
    ]
