# Generated by Django 6.0.1 on 2026-02-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='ADMIN', max_length=10),
        ),
    ]
