# Generated by Django 6.0.1 on 2026-03-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_alter_coursecontent_content_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('Enq_ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('offered_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKEND', 'Weekend'), ('MWF', 'Mon-Wed-Fri'), ('TTS', 'Tue-Thu-Sat')], max_length=20)),
                ('batch_time', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('Walk-in', 'Walk-in'), ('Phone', 'Phone'), ('Website', 'Website'), ('Reference', 'Reference')], max_length=50)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('FOLLOWUP', 'Follow Up'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
    ]
