# Generated by Django 6.0.1 on 2026-03-09 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_followup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='followup_date',
            new_name='next_followup_date',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='followup_time',
            new_name='next_followup_time',
        ),
        migrations.AddField(
            model_name='followup',
            name='done_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followup',
            name='done_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
