# Generated by Django 6.0.1 on 2026-03-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_rename_followup_date_followup_next_followup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
