# Generated by Django 6.0.1 on 2026-03-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_admission_batch_type'),
        ('enquiry', '0005_alter_enquiry_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='total_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='batch_time',
            field=models.CharField(choices=[('09-10', '09:00 AM - 10:00 AM'), ('10-11', '10:00 AM - 11:00 AM'), ('11-12', '11:00 AM - 12:00 PM'), ('12-13', '12:00 PM - 01:00 PM'), ('13-14', '01:00 PM - 02:00 PM'), ('14-15', '02:00 PM - 03:00 PM'), ('15-16', '03:00 PM - 04:00 PM'), ('16-17', '04:00 PM - 05:00 PM'), ('17-18', '05:00 PM - 06:00 PM'), ('18-19', '06:00 PM - 07:00 PM'), ('19-20', '07:00 PM - 08:00 PM'), ('20-21', '08:00 PM - 09:00 PM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='batch_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKEND', 'Weekend'), ('MWF', 'Mon-Wed-Fri'), ('TTS', 'Tue-Thu-Sat')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='interested_course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
