# Generated by Django 6.0.1 on 2026-03-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_admission_batch_type'),
        ('enquiry', '0007_alter_enquiry_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_content',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent'),
        ),
    ]
