# Generated by Django 6.0.1 on 2026-03-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_admission_batch_type'),
        ('enquiry', '0009_alter_enquiry_course_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='course_content',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
    ]
