# Generated by Django 6.0.1 on 2026-03-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_remove_enquiry_course_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='course_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
