# Generated by Django 6.0.1 on 2026-01-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0006_alter_student_address_alter_student_alternate_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('Full', 'Full'), ('Installment', 'Installment')], max_length=20)),
                ('gst', models.BooleanField(default=False)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
