# Generated by Django 6.0.1 on 2026-01-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COURSE', 'Course Added'), ('PAYMENT', 'Payment Added'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='payment_type',
            field=models.CharField(max_length=20),
        ),
    ]
