# Generated by Django 6.0.1 on 2026-01-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_admission_status_alter_admission_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PAID', max_length=10),
        ),
    ]
