# Generated by Django 6.0.1 on 2026-01-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='batch_time',
            field=models.CharField(choices=[('09-10', '09:00 AM - 10:00 AM'), ('10-11', '10:00 AM - 11:00 AM'), ('11-12', '11:00 AM - 12:00 PM'), ('12-13', '12:00 PM - 01:00 PM'), ('13-14', '01:00 PM - 02:00 PM'), ('14-15', '02:00 PM - 03:00 PM'), ('15-16', '03:00 PM - 04:00 PM'), ('16-17', '04:00 PM - 05:00 PM'), ('17-18', '05:00 PM - 06:00 PM'), ('18-19', '06:00 PM - 07:00 PM'), ('19-20', '07:00 PM - 08:00 PM'), ('20-21', '08:00 PM - 09:00 PM')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='batch_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKEND', 'Weekend'), ('MWF', 'Monday / Wednesday / Friday')], max_length=10, null=True),
        ),
    ]
