# Generated by Django 6.0.1 on 2026-02-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_admission_batch_time_admission_batch_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
