# Generated by Django 6.0.1 on 2026-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_installment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_name',
            field=models.TextField(),
        ),
    ]
