# Generated by Django 6.0.1 on 2026-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursecontent_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_name',
            field=models.CharField(max_length=150),
        ),
    ]
