# Generated by Django 6.0.1 on 2026-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursecontent_content_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='batch_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKEND', 'Weekend'), ('MWF', 'Mon-Wed-Fri'), ('TTS', 'Tue-Thu-Sat')], max_length=10, null=True),
        ),
    ]
